### ISSUE TITLE
[Bug] using diferent conda channels leads to issue with conda-store database

### ISSUE THREAD

**Issue by viniciusdc** [conda-incubator/conda-store#275]
When attempting to create an R environment the following error shows up during the build.

```
Traceback (most recent call last):
  File "/opt/conda-store-server/conda_store_server/build.py", line 178, in build_conda_environment
    set_build_completed(conda_store, build, output.encode("utf-8"), packages)
  File "/opt/conda-store-server/conda_store_server/build.py", line 47, in set_build_completed
    raise ValueError(
ValueError: channel url=https://repo.anaconda.com/pkgs/r not recognized in conda-store channel database
```
Conda-Store Server version (based on docker image):
`image: quansight/conda-store-server:v0.3.10` 

There seems to be a check happening in `conda_store_server/build.py` that does not account for external channels (?)

The environment yaml:
```yaml
channels:
  - conda-forge
dependencies:
  - r-base
  - r-irkernel
  - r-ggplot2
  - r-dplyr
  - r-esquisse
  - r-Shiny
  - r-lubridate
  - r-knitr
  - r-mlr
  - r-quanteda
  - r-Caret
  - r-Rmarkdown
  - r-Leaflet
  - r-Janitor
  - r-Corrplot
  - r-Lattice
  - r-GBM
  - r-Prophet
  - r-Randomforest
  - r-C50
  - r-Ggvis
  - r-Plotly
  - r-Rbokeh
  - r-Broom
  - r-StringR
  - r-Magrittr
  - r-Rvest
  - r-Future
  - r-RMySQL
  - r-RSQLite
  - r-Glmnet
  - r-Text2Vec
  - r-SnowballC
  - r-Quantmod
  - r-Rstan
  - r-Swirl
  - r-DBI
  - r-Odbc
  - r-Haven
  - r-Xlconnect
  - r-Xlsx
  - r-Tidyr
  - r-Stringr
  - r-Survival
  - r-Multcomp
  - r-Lme4
  - r-Zoo
  - r-Xts
  - r-Quantmod
  - r-Rcpp
  - r-Devtools
  - r-Testthat
  - r-Roxygen2
  - r-Dalex
  - r-DataExplorer
  - r-Sparklyr
  - r-drake
  - r-tidyverse
name: rkernel
prefix: null
```
