### ISSUE TITLE
Pip section should allow archive urls and filesystem paths

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#342]
Pip allows you to install from archive urls. Currently the following error appears

![image](https://user-images.githubusercontent.com/1740337/177830000-5d36540e-f12b-4265-b422-25f946472cc2.png)

```yaml
name: test
dependencies:
 - pip
 - pip:
    - https://github.com/pallets/flask/archive/refs/tags/2.1.2.zip
    - ./path/to/archive.zip # on local machine
 ```

Would like for the logic in:
  - https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/schema.py#L153-L174 updated so that archive urls are also supported. Likely just some check that it is a valid url or local path using the stdlib.
  - will need to refine the logic here https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/environment.py#L103-L119 on what a pip package is (excluding arguments, archive urls, and filesystem paths).

Generally we would like to handle pip packages similar to how pip normally handles a Requirements.txt file. This may require leveraging the pip library more deeply which I am fine with. Which would certainly be a better fix than what I am suggesting.

Related to https://github.com/Quansight/conda-store/issues/325.
