### ISSUE TITLE
Enable token authentication to private repos

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#497]
Following on to https://github.com/Quansight/conda-store/issues/495 discussion around adding a token to install a package from a private repo... 

When I add a token with the recommended format (see [Read the docs how-to guide for an example](https://docs.readthedocs.io/en/stable/guides/private-python-packages.html)), I get a validation error. 

![image](https://github.com/Quansight/conda-store/assets/15659110/a61bf131-2bfe-49d5-b282-538ccf551331)

**Comment by kcpevey** [comment]
This is blocking #495

**Comment by costrouc** [comment]
@kcpevey I've done some research on this and I think that conda-store actually does support this! I am using pkg_resources and the correct format is https://peps.python.org/pep-0508/.

Example

```yaml
channels:
- conda-forge
dependencies:
- holoviews
- pip:
  - requests @ git+https://github.com/psf/requests.git@main
  - nothing
- ipykernel
```

I've created a PR to add better docs and error messages around the issue.
