### ISSUE TITLE
[BUG] - conda-store doesn't report error in logs when conda-lock poetry has a failure to solve

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#735]
### Describe the bug

Prior to this PR create an environment that can't solve e.g. and the solve with fail and conda-store will not report the build as failed. This happens when you specify a pip package that doesn't exist.

```yaml
name: test
channels:
 - conda-forge
dependencies:
 - python
 - pip
 - pip:
    - numpyyyyy
``` 

### Expected behavior

Solve should succeed

### How to Reproduce the problem?

```yaml
name: test
channels:
 - conda-forge
dependencies:
 - python
 - pip
 - pip:
    - numpyyyyy
```
